name: Publish helm chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '.github/**'         
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - uses: azure/setup-helm@v1
    #   id: installhelm3
    #   with:
    #     version: 'v3.0.3'
    # - name: Publish helm charts
    #   uses: funkypenguin/helm-gh-pages-action@v1.1.1
    #   with:
    #     # A personal access token needed to push your site after it has been built.
    #     access-token: ${{ secrets.CR_TOKEN }}
    #     # The branch expected by GitHub to have the static files needed for your site.
    #     deploy-branch: chart
    #     # The folder in which the helm charts are located
    #     charts-folder: charts

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    # See https://github.com/helm/chart-releaser-action/issues/6
    - name: Install Helm
      run: |
        curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.0.0-rc.1
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"

    # - name: Discord notification
    #   env:
    #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    #   uses: Ilshidur/action-discord@master
    #   with:
    #     args: |
    #       Greetings, geeks!  🤓

    #       A new/updated helm ⎈ chart is fresh out of the oven!
          
    #       Here's what's changed:
    #       > ${{github.event.commits[0].message}}

    #       Get more details at:
    #       {{ EVENT_PAYLOAD.compare }}